### ISSUE TITLE
moveit_setup_assistant does not populate the projection_evaluator and longest_valid_segment_fraction fields

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_ros#12]

**Comment by isucan** [comment]
In the current versions of OMPL those parameters are computed automatically when needed and / or appropriate planner is used (the user does not need to add those fields).  I do not think the setup assistant should set those params since that basically means duplicating functionality from OMPL.

**Comment by sachinchitta** [comment]
When I last ran with the generated files, the planner bringup was crashing without those lines. Adding the lines seemed to bring up - maybe this has been fixed in a newer version?

**Comment by isucan** [comment]
I think this problem persists in the current version. I will fix it.

**Comment by chadrockey** [comment]
Confirmed this is still a problem in latest version.

**Comment by isucan** [comment]
I seem to be unable to replicate this problem. Can you say more about what you mean by 'planner bringup'?
I am running move_group.launch and calling the planners from rviz. When using an unspecified planner, one that works is selected and I get a plan. If I ask the use of a planner that needs a projection I get such errors in move_group:

[ERROR] [1351696305.515275524, 219.355000000]: No default projection is set. Perhaps setup() needs to be called
[ERROR] [1351696305.515558449, 219.356000000]: Exception caught: 'No projection evaluator specified'

Is this not the behaviour you get?

**Comment by isucan** [comment]
bump

**Comment by sachinchitta** [comment]
Ok, I can confirm (in the reachability2 tag) that this actually works without those two lines in the yaml file.
